#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
    exit 1
fi

if [[ ! -f "$1" ]]; then
    exit 1
fi

config=$(python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "$1")
./dashboard.scpt "$config" 
